<?php
class ModelToolFontAwesome extends Model {

	public function getFonts() {
		$fonts = $this->cache->get('fonts');

		if (!$fonts) {
			$fonts = array();

			$fonts[] = array('class' => 'fa-glass','title' => 'Glass');
			$fonts[] = array('class' => 'fa-music','title' => 'Music');
			$fonts[] = array('class' => 'fa-search','title' => 'Search');
			$fonts[] = array('class' => 'fa-envelope-o','title' => 'Envelope O');
			$fonts[] = array('class' => 'fa-heart','title' => 'Heart');
			$fonts[] = array('class' => 'fa-star','title' => 'Star');
			$fonts[] = array('class' => 'fa-star-o','title' => 'Star O');
			$fonts[] = array('class' => 'fa-user','title' => 'User');
			$fonts[] = array('class' => 'fa-film','title' => 'Film');
			$fonts[] = array('class' => 'fa-th-large','title' => 'Th Large');
			$fonts[] = array('class' => 'fa-th','title' => 'Th');
			$fonts[] = array('class' => 'fa-th-list','title' => 'Th List');
			$fonts[] = array('class' => 'fa-check','title' => 'Check');
			$fonts[] = array('class' => 'fa-remove','title' => 'Remove');
			$fonts[] = array('class' => 'fa-close','title' => 'Close');
			$fonts[] = array('class' => 'fa-times','title' => 'Times');
			$fonts[] = array('class' => 'fa-search-plus','title' => 'Search Plus');
			$fonts[] = array('class' => 'fa-search-minus','title' => 'Search Minus');
			$fonts[] = array('class' => 'fa-power-off','title' => 'Power Off');
			$fonts[] = array('class' => 'fa-signal','title' => 'Signal');
			$fonts[] = array('class' => 'fa-gear','title' => 'Gear');
			$fonts[] = array('class' => 'fa-cog','title' => 'Cog');
			$fonts[] = array('class' => 'fa-trash','title' => 'Trash');
			$fonts[] = array('class' => 'fa-home','title' => 'Home');
			$fonts[] = array('class' => 'fa-file-o','title' => 'File O');
			$fonts[] = array('class' => 'fa-clock-o','title' => 'Clock O');
			$fonts[] = array('class' => 'fa-road','title' => 'Road');
			$fonts[] = array('class' => 'fa-download','title' => 'Download');
			$fonts[] = array('class' => 'fa-arrow-circle-o-down','title' => 'Arrow Circle O Down');
			$fonts[] = array('class' => 'fa-arrow-circle-o-up','title' => 'Arrow Circle O Up');
			$fonts[] = array('class' => 'fa-inbox','title' => 'Inbox');
			$fonts[] = array('class' => 'fa-play-circle-o','title' => 'Play Circle O');
			$fonts[] = array('class' => 'fa-rotate-right','title' => 'Rotate Right');
			$fonts[] = array('class' => 'fa-repeat','title' => 'Repeat');
			$fonts[] = array('class' => 'fa-refresh','title' => 'Refresh');
			$fonts[] = array('class' => 'fa-list-alt','title' => 'List Alt');
			$fonts[] = array('class' => 'fa-lock','title' => 'Lock');
			$fonts[] = array('class' => 'fa-flag','title' => 'Flag');
			$fonts[] = array('class' => 'fa-headphones','title' => 'Headphones');
			$fonts[] = array('class' => 'fa-volume-off','title' => 'Volume Off');
			$fonts[] = array('class' => 'fa-volume-down','title' => 'Volume Down');
			$fonts[] = array('class' => 'fa-volume-up','title' => 'Volume Up');
			$fonts[] = array('class' => 'fa-qrcode','title' => 'QR Code');
			$fonts[] = array('class' => 'fa-barcode','title' => 'Barcode');
			$fonts[] = array('class' => 'fa-tag','title' => 'Tag');
			$fonts[] = array('class' => 'fa-tags','title' => 'Tags');
			$fonts[] = array('class' => 'fa-book','title' => 'Book');
			$fonts[] = array('class' => 'fa-bookmark','title' => 'Bookmark');
			$fonts[] = array('class' => 'fa-print','title' => 'Print');
			$fonts[] = array('class' => 'fa-camera','title' => 'Camera');
			$fonts[] = array('class' => 'fa-font','title' => 'Font');
			$fonts[] = array('class' => 'fa-bold','title' => 'Bold');
			$fonts[] = array('class' => 'fa-italic','title' => 'Italic');
			$fonts[] = array('class' => 'fa-text-height','title' => 'Text Height');
			$fonts[] = array('class' => 'fa-text-width','title' => 'Text Width');
			$fonts[] = array('class' => 'fa-align-left','title' => 'Align Left');
			$fonts[] = array('class' => 'fa-align-center','title' => 'Align Center');
			$fonts[] = array('class' => 'fa-align-right','title' => 'Align Right');
			$fonts[] = array('class' => 'fa-align-justify','title' => 'Align Justify');
			$fonts[] = array('class' => 'fa-list','title' => 'List');
			$fonts[] = array('class' => 'fa-dedent','title' => 'Dedent');
			$fonts[] = array('class' => 'fa-outdent','title' => 'Outdent');
			$fonts[] = array('class' => 'fa-indent','title' => 'Indent');
			$fonts[] = array('class' => 'fa-video-camera','title' => 'Video Camera');
			$fonts[] = array('class' => 'fa-photo','title' => 'Photo');
			$fonts[] = array('class' => 'fa-image','title' => 'Image');
			$fonts[] = array('class' => 'fa-picture-o','title' => 'Picture O');
			$fonts[] = array('class' => 'fa-pencil','title' => 'Pencil');
			$fonts[] = array('class' => 'fa-map-marker','title' => 'Map Marker');
			$fonts[] = array('class' => 'fa-adjust','title' => 'Adjust');
			$fonts[] = array('class' => 'fa-tint','title' => 'Tint');
			$fonts[] = array('class' => 'fa-edit','title' => 'Edit');
			$fonts[] = array('class' => 'fa-pencil-square-o','title' => 'Pencil Square O');
			$fonts[] = array('class' => 'fa-share-square-o','title' => 'Share Square O');
			$fonts[] = array('class' => 'fa-check-square-o','title' => 'Check Square O');
			$fonts[] = array('class' => 'fa-arrows','title' => 'Arrows');
			$fonts[] = array('class' => 'fa-step-backward','title' => 'Step Backward');
			$fonts[] = array('class' => 'fa-fast-backward','title' => 'Fast Backward');
			$fonts[] = array('class' => 'fa-backward','title' => 'Backward');
			$fonts[] = array('class' => 'fa-play','title' => 'Play');
			$fonts[] = array('class' => 'fa-pause','title' => 'Pause');
			$fonts[] = array('class' => 'fa-stop','title' => 'Stop');
			$fonts[] = array('class' => 'fa-forward','title' => 'Forward');
			$fonts[] = array('class' => 'fa-fast-forward','title' => 'Fast Forward');
			$fonts[] = array('class' => 'fa-step-forward','title' => 'Step Forward');
			$fonts[] = array('class' => 'fa-eject','title' => 'Eject');
			$fonts[] = array('class' => 'fa-chevron-left','title' => 'Chevron Left');
			$fonts[] = array('class' => 'fa-chevron-right','title' => 'Chevron Right');
			$fonts[] = array('class' => 'fa-plus-circle','title' => 'Plus Circle');
			$fonts[] = array('class' => 'fa-minus-circle','title' => 'Minus Circle');
			$fonts[] = array('class' => 'fa-times-circle','title' => 'Times Circle');
			$fonts[] = array('class' => 'fa-check-circle','title' => 'Check Circle');
			$fonts[] = array('class' => 'fa-question-circle','title' => 'Question Circle');
			$fonts[] = array('class' => 'fa-info-circle','title' => 'Info Circle');
			$fonts[] = array('class' => 'fa-crosshairs','title' => 'Crosshairs');
			$fonts[] = array('class' => 'fa-times-circle-o','title' => 'Times Circle O');
			$fonts[] = array('class' => 'fa-check-circle-o','title' => 'Check Circle O');
			$fonts[] = array('class' => 'fa-ban','title' => 'Ban');
			$fonts[] = array('class' => 'fa-arrow-left','title' => 'Arrow Left');
			$fonts[] = array('class' => 'fa-arrow-right','title' => 'Arrow Right');
			$fonts[] = array('class' => 'fa-arrow-up','title' => 'Arrow Up');
			$fonts[] = array('class' => 'fa-arrow-down','title' => 'Arrow Down');
			$fonts[] = array('class' => 'fa-mail-forward','title' => 'Mail Forward');
			$fonts[] = array('class' => 'fa-share','title' => 'Share');
			$fonts[] = array('class' => 'fa-expand','title' => 'Expand');
			$fonts[] = array('class' => 'fa-compress','title' => 'Compress');
			$fonts[] = array('class' => 'fa-plus','title' => 'Plus');
			$fonts[] = array('class' => 'fa-minus','title' => 'Minus');
			$fonts[] = array('class' => 'fa-asterisk','title' => 'Asterisk');
			$fonts[] = array('class' => 'fa-exclamation-circle','title' => 'Exclamation Circle');
			$fonts[] = array('class' => 'fa-gift','title' => 'Gift');
			$fonts[] = array('class' => 'fa-leaf','title' => 'Leaf');
			$fonts[] = array('class' => 'fa-fire','title' => 'Fire');
			$fonts[] = array('class' => 'fa-eye','title' => 'Eye');
			$fonts[] = array('class' => 'fa-eye-slash','title' => 'Eye Slash');
			$fonts[] = array('class' => 'fa-warning','title' => 'Warning');
			$fonts[] = array('class' => 'fa-exclamation-triangle','title' => 'Exclamation Triangle');
			$fonts[] = array('class' => 'fa-plane','title' => 'Plane');
			$fonts[] = array('class' => 'fa-calendar','title' => 'Calendar');
			$fonts[] = array('class' => 'fa-random','title' => 'Random');
			$fonts[] = array('class' => 'fa-comment','title' => 'Comment');
			$fonts[] = array('class' => 'fa-magnet','title' => 'Magnet');
			$fonts[] = array('class' => 'fa-chevron-up','title' => 'Chevron Up');
			$fonts[] = array('class' => 'fa-chevron-down','title' => 'Chevron Down');
			$fonts[] = array('class' => 'fa-retweet','title' => 'Retweet');
			$fonts[] = array('class' => 'fa-shopping-cart','title' => 'Shopping Cart');
			$fonts[] = array('class' => 'fa-folder','title' => 'Folder');
			$fonts[] = array('class' => 'fa-folder-open','title' => 'Folder Open');
			$fonts[] = array('class' => 'fa-arrows-v','title' => 'Arrows V');
			$fonts[] = array('class' => 'fa-arrows-h','title' => 'Arrows H');
			$fonts[] = array('class' => 'fa-bar-chart-o','title' => 'Bar Chart O');
			$fonts[] = array('class' => 'fa-bar-chart','title' => 'Bar Chart');
			$fonts[] = array('class' => 'fa-twitter-square','title' => 'Twitter Square');
			$fonts[] = array('class' => 'fa-facebook-square','title' => 'Facebook Square');
			$fonts[] = array('class' => 'fa-camera-retro','title' => 'Camera Retro');
			$fonts[] = array('class' => 'fa-key','title' => 'Key');
			$fonts[] = array('class' => 'fa-gears','title' => 'Gears');
			$fonts[] = array('class' => 'fa-cogs','title' => 'Cogs');
			$fonts[] = array('class' => 'fa-comments','title' => 'Comments');
			$fonts[] = array('class' => 'fa-thumbs-o-up','title' => 'Thumbs O Up');
			$fonts[] = array('class' => 'fa-thumbs-o-down','title' => 'Thumbs O Down');
			$fonts[] = array('class' => 'fa-star-half','title' => 'Star Half');
			$fonts[] = array('class' => 'fa-heart-o','title' => 'Heart O');
			$fonts[] = array('class' => 'fa-sign-out','title' => 'Sign Out');
			$fonts[] = array('class' => 'fa-linkedin-square','title' => 'LinkedIn Square');
			$fonts[] = array('class' => 'fa-thumb-tack','title' => 'Thumb Tack');
			$fonts[] = array('class' => 'fa-external-link','title' => 'External Link');
			$fonts[] = array('class' => 'fa-sign-in','title' => 'Sign In');
			$fonts[] = array('class' => 'fa-trophy','title' => 'Trophy');
			$fonts[] = array('class' => 'fa-github-square','title' => 'Github Square');
			$fonts[] = array('class' => 'fa-upload','title' => 'Upload');
			$fonts[] = array('class' => 'fa-lemon-o','title' => 'Lemon O');
			$fonts[] = array('class' => 'fa-phone','title' => 'Phone');
			$fonts[] = array('class' => 'fa-square-o','title' => 'Square O');
			$fonts[] = array('class' => 'fa-bookmark-o','title' => 'Bookmark O');
			$fonts[] = array('class' => 'fa-phone-square','title' => 'Phone Square');
			$fonts[] = array('class' => 'fa-twitter','title' => 'Twitter');
			$fonts[] = array('class' => 'fa-facebook-f','title' => 'Facebook F');
			$fonts[] = array('class' => 'fa-facebook','title' => 'Facebook');
			$fonts[] = array('class' => 'fa-github','title' => 'Github');
			$fonts[] = array('class' => 'fa-unlock','title' => 'Unlock');
			$fonts[] = array('class' => 'fa-credit-card','title' => 'Credit Card');
			$fonts[] = array('class' => 'fa-feed','title' => 'Feed');
			$fonts[] = array('class' => 'fa-rss','title' => 'Rss');
			$fonts[] = array('class' => 'fa-hdd-o','title' => 'Hdd O');
			$fonts[] = array('class' => 'fa-bullhorn','title' => 'Bullhorn');
			$fonts[] = array('class' => 'fa-bell','title' => 'Bell');
			$fonts[] = array('class' => 'fa-certificate','title' => 'Certificate');
			$fonts[] = array('class' => 'fa-hand-o-right','title' => 'Hand O Right');
			$fonts[] = array('class' => 'fa-hand-o-left','title' => 'Hand O Left');
			$fonts[] = array('class' => 'fa-hand-o-up','title' => 'Hand O Up');
			$fonts[] = array('class' => 'fa-hand-o-down','title' => 'Hand O Down');
			$fonts[] = array('class' => 'fa-arrow-circle-left','title' => 'Arrow Circle Left');
			$fonts[] = array('class' => 'fa-arrow-circle-right','title' => 'Arrow Circle Right');
			$fonts[] = array('class' => 'fa-arrow-circle-up','title' => 'Arrow Circle Up');
			$fonts[] = array('class' => 'fa-arrow-circle-down','title' => 'Arrow Circle Down');
			$fonts[] = array('class' => 'fa-globe','title' => 'Globe');
			$fonts[] = array('class' => 'fa-wrench','title' => 'Wrench');
			$fonts[] = array('class' => 'fa-tasks','title' => 'Tasks');
			$fonts[] = array('class' => 'fa-filter','title' => 'Filter');
			$fonts[] = array('class' => 'fa-briefcase','title' => 'Briefcase');
			$fonts[] = array('class' => 'fa-arrows-alt','title' => 'Arrows Alt');
			$fonts[] = array('class' => 'fa-group','title' => 'Group');
			$fonts[] = array('class' => 'fa-users','title' => 'Users');
			$fonts[] = array('class' => 'fa-chain','title' => 'Chain');
			$fonts[] = array('class' => 'fa-link','title' => 'Link');
			$fonts[] = array('class' => 'fa-cloud','title' => 'Cloud');
			$fonts[] = array('class' => 'fa-flask','title' => 'Flask');
			$fonts[] = array('class' => 'fa-cut','title' => 'Cut');
			$fonts[] = array('class' => 'fa-scissors','title' => 'Scissors');
			$fonts[] = array('class' => 'fa-copy','title' => 'Copy');
			$fonts[] = array('class' => 'fa-files-o','title' => 'Files O');
			$fonts[] = array('class' => 'fa-paperclip','title' => 'Paperclip');
			$fonts[] = array('class' => 'fa-save','title' => 'Save');
			$fonts[] = array('class' => 'fa-floppy-o','title' => 'Floppy O');
			$fonts[] = array('class' => 'fa-square','title' => 'Square');
			$fonts[] = array('class' => 'fa-navicon','title' => 'Navicon');
			$fonts[] = array('class' => 'fa-reorder','title' => 'Reorder');
			$fonts[] = array('class' => 'fa-bars','title' => 'Bars');
			$fonts[] = array('class' => 'fa-list-ul','title' => 'List Ul');
			$fonts[] = array('class' => 'fa-list-ol','title' => 'List Ol');
			$fonts[] = array('class' => 'fa-strikethrough','title' => 'Strikethrough');
			$fonts[] = array('class' => 'fa-underline','title' => 'Underline');
			$fonts[] = array('class' => 'fa-table','title' => 'Table');
			$fonts[] = array('class' => 'fa-magic','title' => 'Magic');
			$fonts[] = array('class' => 'fa-truck','title' => 'Truck');
			$fonts[] = array('class' => 'fa-pinterest','title' => 'Pinterest');
			$fonts[] = array('class' => 'fa-pinterest-square','title' => 'Pinterest Square');
			$fonts[] = array('class' => 'fa-google-plus-square','title' => 'Google Plus Square');
			$fonts[] = array('class' => 'fa-google-plus','title' => 'Google Plus');
			$fonts[] = array('class' => 'fa-money','title' => 'Money');
			$fonts[] = array('class' => 'fa-caret-down','title' => 'Caret Down');
			$fonts[] = array('class' => 'fa-caret-up','title' => 'Caret Up');
			$fonts[] = array('class' => 'fa-caret-left','title' => 'Caret Left');
			$fonts[] = array('class' => 'fa-caret-right','title' => 'Caret Right');
			$fonts[] = array('class' => 'fa-columns','title' => 'Columns');
			$fonts[] = array('class' => 'fa-unsorted','title' => 'Unsorted');
			$fonts[] = array('class' => 'fa-sort','title' => 'Sort');
			$fonts[] = array('class' => 'fa-sort-down','title' => 'Sort Down');
			$fonts[] = array('class' => 'fa-sort-desc','title' => 'Sort Desc');
			$fonts[] = array('class' => 'fa-sort-up','title' => 'Sort Up');
			$fonts[] = array('class' => 'fa-sort-asc','title' => 'Sort Asc');
			$fonts[] = array('class' => 'fa-envelope','title' => 'Envelope');
			$fonts[] = array('class' => 'fa-linkedin','title' => 'LinkedIn');
			$fonts[] = array('class' => 'fa-rotate-left','title' => 'Rotate Left');
			$fonts[] = array('class' => 'fa-undo','title' => 'Undo');
			$fonts[] = array('class' => 'fa-legal','title' => 'Legal');
			$fonts[] = array('class' => 'fa-gavel','title' => 'Gavel');
			$fonts[] = array('class' => 'fa-dashboard','title' => 'Dashboard');
			$fonts[] = array('class' => 'fa-tachometer','title' => 'Tachometer');
			$fonts[] = array('class' => 'fa-comment-o','title' => 'Comment O');
			$fonts[] = array('class' => 'fa-comments-o','title' => 'Comments O');
			$fonts[] = array('class' => 'fa-flash','title' => 'Flash');
			$fonts[] = array('class' => 'fa-bolt','title' => 'Bolt');
			$fonts[] = array('class' => 'fa-sitemap','title' => 'Sitemap');
			$fonts[] = array('class' => 'fa-umbrella','title' => 'Umbrella');
			$fonts[] = array('class' => 'fa-paste','title' => 'Paste');
			$fonts[] = array('class' => 'fa-clipboard','title' => 'Clipboard');
			$fonts[] = array('class' => 'fa-lightbulb-o','title' => 'Lightbulb O');
			$fonts[] = array('class' => 'fa-exchange','title' => 'Exchange');
			$fonts[] = array('class' => 'fa-cloud-download','title' => 'Cloud Download');
			$fonts[] = array('class' => 'fa-cloud-upload','title' => 'Cloud Upload');
			$fonts[] = array('class' => 'fa-user-md','title' => 'User Md');
			$fonts[] = array('class' => 'fa-stethoscope','title' => 'Stethoscope');
			$fonts[] = array('class' => 'fa-suitcase','title' => 'Suitcase');
			$fonts[] = array('class' => 'fa-bell-o','title' => 'Bell O');
			$fonts[] = array('class' => 'fa-coffee','title' => 'Coffee');
			$fonts[] = array('class' => 'fa-cutlery','title' => 'Cutlery');
			$fonts[] = array('class' => 'fa-file-text-o','title' => 'File Text O');
			$fonts[] = array('class' => 'fa-building-o','title' => 'Building O');
			$fonts[] = array('class' => 'fa-hospital-o','title' => 'Hospital O');
			$fonts[] = array('class' => 'fa-ambulance','title' => 'Ambulance');
			$fonts[] = array('class' => 'fa-medkit','title' => 'Med Kit');
			$fonts[] = array('class' => 'fa-fighter-jet','title' => 'Fighter Jet');
			$fonts[] = array('class' => 'fa-beer','title' => 'Beer');
			$fonts[] = array('class' => 'fa-h-square','title' => 'H Square');
			$fonts[] = array('class' => 'fa-plus-square','title' => 'Plus Square');
			$fonts[] = array('class' => 'fa-angle-double-left','title' => 'Angle Double Left');
			$fonts[] = array('class' => 'fa-angle-double-right','title' => 'Angle Double Right');
			$fonts[] = array('class' => 'fa-angle-double-up','title' => 'Angle Double Up');
			$fonts[] = array('class' => 'fa-angle-double-down','title' => 'Angle Double Down');
			$fonts[] = array('class' => 'fa-angle-left','title' => 'Angle Left');
			$fonts[] = array('class' => 'fa-angle-right','title' => 'Angle Right');
			$fonts[] = array('class' => 'fa-angle-up','title' => 'Angle Up');
			$fonts[] = array('class' => 'fa-angle-down','title' => 'Angle Down');
			$fonts[] = array('class' => 'fa-desktop','title' => 'Desktop');
			$fonts[] = array('class' => 'fa-laptop','title' => 'Laptop');
			$fonts[] = array('class' => 'fa-tablet','title' => 'Tablet');
			$fonts[] = array('class' => 'fa-mobile-phone','title' => 'Mobile Phone');
			$fonts[] = array('class' => 'fa-mobile','title' => 'Mobile');
			$fonts[] = array('class' => 'fa-circle-o','title' => 'Circle O');
			$fonts[] = array('class' => 'fa-quote-left','title' => 'Quote Left');
			$fonts[] = array('class' => 'fa-quote-right','title' => 'Quote Right');
			$fonts[] = array('class' => 'fa-spinner','title' => 'Spinner');
			$fonts[] = array('class' => 'fa-circle','title' => 'Circle');
			$fonts[] = array('class' => 'fa-mail-reply','title' => 'Mail Reply');
			$fonts[] = array('class' => 'fa-reply','title' => 'Reply');
			$fonts[] = array('class' => 'fa-github-alt','title' => 'Github Alt');
			$fonts[] = array('class' => 'fa-folder-o','title' => 'Folder O');
			$fonts[] = array('class' => 'fa-folder-open-o','title' => 'Folder Open O');
			$fonts[] = array('class' => 'fa-smile-o','title' => 'Smile O');
			$fonts[] = array('class' => 'fa-frown-o','title' => 'Frown O');
			$fonts[] = array('class' => 'fa-meh-o','title' => 'Meh O');
			$fonts[] = array('class' => 'fa-gamepad','title' => 'Gamepad');
			$fonts[] = array('class' => 'fa-keyboard-o','title' => 'Keyboard O');
			$fonts[] = array('class' => 'fa-flag-o','title' => 'Flag O');
			$fonts[] = array('class' => 'fa-flag-checkered','title' => 'Flag Checkered');
			$fonts[] = array('class' => 'fa-terminal','title' => 'Terminal');
			$fonts[] = array('class' => 'fa-code','title' => 'Code');
			$fonts[] = array('class' => 'fa-mail-reply-all','title' => 'Mail Reply All');
			$fonts[] = array('class' => 'fa-reply-all','title' => 'Reply All');
			$fonts[] = array('class' => 'fa-star-half-empty','title' => 'Star Half Empty');
			$fonts[] = array('class' => 'fa-star-half-full','title' => 'Star Half Full');
			$fonts[] = array('class' => 'fa-star-half-o','title' => 'Star Half O');
			$fonts[] = array('class' => 'fa-location-arrow','title' => 'Location Arrow');
			$fonts[] = array('class' => 'fa-crop','title' => 'Crop');
			$fonts[] = array('class' => 'fa-code-fork','title' => 'Code Fork');
			$fonts[] = array('class' => 'fa-unlink','title' => 'Unlink');
			$fonts[] = array('class' => 'fa-chain-broken','title' => 'Chain Broken');
			$fonts[] = array('class' => 'fa-question','title' => 'Question');
			$fonts[] = array('class' => 'fa-info','title' => 'Info');
			$fonts[] = array('class' => 'fa-exclamation','title' => 'Exclamation');
			$fonts[] = array('class' => 'fa-superscript','title' => 'Superscript');
			$fonts[] = array('class' => 'fa-subscript','title' => 'Subscript');
			$fonts[] = array('class' => 'fa-eraser','title' => 'Eraser');
			$fonts[] = array('class' => 'fa-puzzle-piece','title' => 'Puzzle Piece');
			$fonts[] = array('class' => 'fa-microphone','title' => 'Microphone');
			$fonts[] = array('class' => 'fa-microphone-slash','title' => 'Microphone Slash');
			$fonts[] = array('class' => 'fa-shield','title' => 'Shield');
			$fonts[] = array('class' => 'fa-calendar-o','title' => 'Calendar O');
			$fonts[] = array('class' => 'fa-fire-extinguisher','title' => 'Fire Extinguisher');
			$fonts[] = array('class' => 'fa-rocket','title' => 'Rocket');
			$fonts[] = array('class' => 'fa-maxcdn','title' => 'Maxcdn');
			$fonts[] = array('class' => 'fa-chevron-circle-left','title' => 'Chevron Circle Left');
			$fonts[] = array('class' => 'fa-chevron-circle-right','title' => 'Chevron Circle Right');
			$fonts[] = array('class' => 'fa-chevron-circle-up','title' => 'Chevron Circle Up');
			$fonts[] = array('class' => 'fa-chevron-circle-down','title' => 'Chevron Circle Down');
			$fonts[] = array('class' => 'fa-html5','title' => 'Html5');
			$fonts[] = array('class' => 'fa-css3','title' => 'Css3');
			$fonts[] = array('class' => 'fa-anchor','title' => 'Anchor');
			$fonts[] = array('class' => 'fa-unlock-alt','title' => 'Unlock Alt');
			$fonts[] = array('class' => 'fa-bullseye','title' => 'Bullseye');
			$fonts[] = array('class' => 'fa-ellipsis-h','title' => 'Ellipsis H');
			$fonts[] = array('class' => 'fa-ellipsis-v','title' => 'Ellipsis V');
			$fonts[] = array('class' => 'fa-rss-square','title' => 'Rss Square');
			$fonts[] = array('class' => 'fa-play-circle','title' => 'Play Circle');
			$fonts[] = array('class' => 'fa-minus-square','title' => 'Minus Square');
			$fonts[] = array('class' => 'fa-minus-square-o','title' => 'Minus Square O');
			$fonts[] = array('class' => 'fa-level-up','title' => 'Level Up');
			$fonts[] = array('class' => 'fa-level-down','title' => 'Level Down');
			$fonts[] = array('class' => 'fa-check-square','title' => 'Check Square');
			$fonts[] = array('class' => 'fa-pencil-square','title' => 'Pencil Square');
			$fonts[] = array('class' => 'fa-external-link-square','title' => 'External Link Square');
			$fonts[] = array('class' => 'fa-share-square','title' => 'Share Square');
			$fonts[] = array('class' => 'fa-compass','title' => 'Compass');
			$fonts[] = array('class' => 'fa-toggle-down','title' => 'Toggle Down');
			$fonts[] = array('class' => 'fa-caret-square-o-down','title' => 'Caret Square O Down');
			$fonts[] = array('class' => 'fa-toggle-up','title' => 'Toggle Up');
			$fonts[] = array('class' => 'fa-caret-square-o-up','title' => 'Caret Square O Up');
			$fonts[] = array('class' => 'fa-toggle-right','title' => 'Toggle Right');
			$fonts[] = array('class' => 'fa-caret-square-o-right','title' => 'Caret Square O Right');
			$fonts[] = array('class' => 'fa-euro','title' => 'Euro');
			$fonts[] = array('class' => 'fa-eur','title' => 'EUR');
			$fonts[] = array('class' => 'fa-gbp','title' => 'GBP');
			$fonts[] = array('class' => 'fa-dollar','title' => 'Dollar');
			$fonts[] = array('class' => 'fa-usd','title' => 'USD');
			$fonts[] = array('class' => 'fa-rupee','title' => 'Rupee');
			$fonts[] = array('class' => 'fa-inr','title' => 'INR');
			$fonts[] = array('class' => 'fa-cny','title' => 'CNY');
			$fonts[] = array('class' => 'fa-rmb','title' => 'RMB');
			$fonts[] = array('class' => 'fa-yen','title' => 'Yen');
			$fonts[] = array('class' => 'fa-jpy','title' => 'JPY');
			$fonts[] = array('class' => 'fa-ruble','title' => 'Ruble');
			$fonts[] = array('class' => 'fa-rouble','title' => 'Rouble');
			$fonts[] = array('class' => 'fa-rub','title' => 'RUB');
			$fonts[] = array('class' => 'fa-won','title' => 'Won');
			$fonts[] = array('class' => 'fa-krw','title' => 'KRW');
			$fonts[] = array('class' => 'fa-bitcoin','title' => 'Bitcoin');
			$fonts[] = array('class' => 'fa-btc','title' => 'BTC');
			$fonts[] = array('class' => 'fa-file','title' => 'File');
			$fonts[] = array('class' => 'fa-file-text','title' => 'File Text');
			$fonts[] = array('class' => 'fa-sort-alpha-asc','title' => 'Sort Alpha Asc');
			$fonts[] = array('class' => 'fa-sort-alpha-desc','title' => 'Sort Alpha Desc');
			$fonts[] = array('class' => 'fa-sort-amount-asc','title' => 'Sort Amount Asc');
			$fonts[] = array('class' => 'fa-sort-amount-desc','title' => 'Sort Amount Desc');
			$fonts[] = array('class' => 'fa-sort-numeric-asc','title' => 'Sort Numeric Asc');
			$fonts[] = array('class' => 'fa-sort-numeric-desc','title' => 'Sort Numeric Desc');
			$fonts[] = array('class' => 'fa-thumbs-up','title' => 'Thumbs Up');
			$fonts[] = array('class' => 'fa-thumbs-down','title' => 'Thumbs Down');
			$fonts[] = array('class' => 'fa-youtube-square','title' => 'YouTube Square');
			$fonts[] = array('class' => 'fa-youtube','title' => 'YouTube');
			$fonts[] = array('class' => 'fa-xing','title' => 'Xing');
			$fonts[] = array('class' => 'fa-xing-square','title' => 'Xing Square');
			$fonts[] = array('class' => 'fa-youtube-play','title' => 'YouTube Play');
			$fonts[] = array('class' => 'fa-dropbox','title' => 'Dropbox');
			$fonts[] = array('class' => 'fa-stack-overflow','title' => 'Stack Overflow');
			$fonts[] = array('class' => 'fa-instagram','title' => 'Instagram');
			$fonts[] = array('class' => 'fa-flickr','title' => 'Flickr');
			$fonts[] = array('class' => 'fa-adn','title' => 'Adn');
			$fonts[] = array('class' => 'fa-bitbucket','title' => 'Bitbucket');
			$fonts[] = array('class' => 'fa-bitbucket-square','title' => 'Bitbucket Square');
			$fonts[] = array('class' => 'fa-tumblr','title' => 'Tumblr');
			$fonts[] = array('class' => 'fa-tumblr-square','title' => 'Tumblr Square');
			$fonts[] = array('class' => 'fa-long-arrow-down','title' => 'Long Arrow Down');
			$fonts[] = array('class' => 'fa-long-arrow-up','title' => 'Long Arrow Up');
			$fonts[] = array('class' => 'fa-long-arrow-left','title' => 'Long Arrow Left');
			$fonts[] = array('class' => 'fa-long-arrow-right','title' => 'Long Arrow Right');
			$fonts[] = array('class' => 'fa-apple','title' => 'Apple');
			$fonts[] = array('class' => 'fa-windows','title' => 'Windows');
			$fonts[] = array('class' => 'fa-android','title' => 'Android');
			$fonts[] = array('class' => 'fa-linux','title' => 'Linux');
			$fonts[] = array('class' => 'fa-dribbble','title' => 'Dribbble');
			$fonts[] = array('class' => 'fa-skype','title' => 'Skype');
			$fonts[] = array('class' => 'fa-foursquare','title' => 'Foursquare');
			$fonts[] = array('class' => 'fa-trello','title' => 'Trello');
			$fonts[] = array('class' => 'fa-female','title' => 'Female');
			$fonts[] = array('class' => 'fa-male','title' => 'Male');
			$fonts[] = array('class' => 'fa-gittip','title' => 'Gittip');
			$fonts[] = array('class' => 'fa-gratipay','title' => 'Gratipay');
			$fonts[] = array('class' => 'fa-sun-o','title' => 'Sun O');
			$fonts[] = array('class' => 'fa-moon-o','title' => 'Moon O');
			$fonts[] = array('class' => 'fa-archive','title' => 'Archive');
			$fonts[] = array('class' => 'fa-bug','title' => 'Bug');
			$fonts[] = array('class' => 'fa-vk','title' => 'Vk');
			$fonts[] = array('class' => 'fa-weibo','title' => 'Weibo');
			$fonts[] = array('class' => 'fa-renren','title' => 'Renren');
			$fonts[] = array('class' => 'fa-pagelines','title' => 'Pagelines');
			$fonts[] = array('class' => 'fa-stack-exchange','title' => 'Stack Exchange');
			$fonts[] = array('class' => 'fa-arrow-circle-o-right','title' => 'Arrow Circle O Right');
			$fonts[] = array('class' => 'fa-arrow-circle-o-left','title' => 'Arrow Circle O Left');
			$fonts[] = array('class' => 'fa-toggle-left','title' => 'Toggle Left');
			$fonts[] = array('class' => 'fa-caret-square-o-left','title' => 'Caret Square O Left');
			$fonts[] = array('class' => 'fa-dot-circle-o','title' => 'Dot Circle O');
			$fonts[] = array('class' => 'fa-wheelchair','title' => 'Wheelchair');
			$fonts[] = array('class' => 'fa-vimeo-square','title' => 'Vimeo Square');
			$fonts[] = array('class' => 'fa-turkish-lira','title' => 'Turkish Lira');
			$fonts[] = array('class' => 'fa-try','title' => 'TRY');
			$fonts[] = array('class' => 'fa-plus-square-o','title' => 'Plus Square O');
			$fonts[] = array('class' => 'fa-space-shuttle','title' => 'Space Shuttle');
			$fonts[] = array('class' => 'fa-slack','title' => 'Slack');
			$fonts[] = array('class' => 'fa-envelope-square','title' => 'Envelope Square');
			$fonts[] = array('class' => 'fa-wordpress','title' => 'Wordpress');
			$fonts[] = array('class' => 'fa-openid','title' => 'OpenId');
			$fonts[] = array('class' => 'fa-institution','title' => 'Institution');
			$fonts[] = array('class' => 'fa-bank','title' => 'Bank');
			$fonts[] = array('class' => 'fa-university','title' => 'University');
			$fonts[] = array('class' => 'fa-mortar-board','title' => 'Mortar Board');
			$fonts[] = array('class' => 'fa-graduation-cap','title' => 'Graduation Cap');
			$fonts[] = array('class' => 'fa-yahoo','title' => 'Yahoo');
			$fonts[] = array('class' => 'fa-google','title' => 'Google');
			$fonts[] = array('class' => 'fa-reddit','title' => 'Reddit');
			$fonts[] = array('class' => 'fa-reddit-square','title' => 'Reddit Square');
			$fonts[] = array('class' => 'fa-stumbleupon-circle','title' => 'Stumbleupon Circle');
			$fonts[] = array('class' => 'fa-stumbleupon','title' => 'Stumbleupon');
			$fonts[] = array('class' => 'fa-delicious','title' => 'Delicious');
			$fonts[] = array('class' => 'fa-digg','title' => 'Digg');
			$fonts[] = array('class' => 'fa-pied-piper-pp','title' => 'Pied Piper Pp');
			$fonts[] = array('class' => 'fa-pied-piper-alt','title' => 'Pied Piper Alt');
			$fonts[] = array('class' => 'fa-drupal','title' => 'Drupal');
			$fonts[] = array('class' => 'fa-joomla','title' => 'Joomla');
			$fonts[] = array('class' => 'fa-language','title' => 'Language');
			$fonts[] = array('class' => 'fa-fax','title' => 'Fax');
			$fonts[] = array('class' => 'fa-building','title' => 'Building');
			$fonts[] = array('class' => 'fa-child','title' => 'Child');
			$fonts[] = array('class' => 'fa-paw','title' => 'Paw');
			$fonts[] = array('class' => 'fa-spoon','title' => 'Spoon');
			$fonts[] = array('class' => 'fa-cube','title' => 'Cube');
			$fonts[] = array('class' => 'fa-cubes','title' => 'Cubes');
			$fonts[] = array('class' => 'fa-behance','title' => 'Behance');
			$fonts[] = array('class' => 'fa-behance-square','title' => 'Behance Square');
			$fonts[] = array('class' => 'fa-steam','title' => 'Steam');
			$fonts[] = array('class' => 'fa-steam-square','title' => 'Steam Square');
			$fonts[] = array('class' => 'fa-recycle','title' => 'Recycle');
			$fonts[] = array('class' => 'fa-automobile','title' => 'Automobile');
			$fonts[] = array('class' => 'fa-car','title' => 'Car');
			$fonts[] = array('class' => 'fa-cab','title' => 'Cab');
			$fonts[] = array('class' => 'fa-taxi','title' => 'Taxi');
			$fonts[] = array('class' => 'fa-tree','title' => 'Tree');
			$fonts[] = array('class' => 'fa-spotify','title' => 'Spotify');
			$fonts[] = array('class' => 'fa-deviantart','title' => 'DeviantArt');
			$fonts[] = array('class' => 'fa-soundcloud','title' => 'SoundCloud');
			$fonts[] = array('class' => 'fa-database','title' => 'Database');
			$fonts[] = array('class' => 'fa-file-pdf-o','title' => 'File Pdf O');
			$fonts[] = array('class' => 'fa-file-word-o','title' => 'File Word O');
			$fonts[] = array('class' => 'fa-file-excel-o','title' => 'File Excel O');
			$fonts[] = array('class' => 'fa-file-powerpoint-o','title' => 'File Powerpoint O');
			$fonts[] = array('class' => 'fa-file-photo-o','title' => 'File Photo O');
			$fonts[] = array('class' => 'fa-file-picture-o','title' => 'File Picture O');
			$fonts[] = array('class' => 'fa-file-image-o','title' => 'File Image O');
			$fonts[] = array('class' => 'fa-file-zip-o','title' => 'File Zip O');
			$fonts[] = array('class' => 'fa-file-archive-o','title' => 'File Archive O');
			$fonts[] = array('class' => 'fa-file-sound-o','title' => 'File Sound O');
			$fonts[] = array('class' => 'fa-file-audio-o','title' => 'File Audio O');
			$fonts[] = array('class' => 'fa-file-movie-o','title' => 'File Movie O');
			$fonts[] = array('class' => 'fa-file-video-o','title' => 'File Video O');
			$fonts[] = array('class' => 'fa-file-code-o','title' => 'File Code O');
			$fonts[] = array('class' => 'fa-vine','title' => 'Vine');
			$fonts[] = array('class' => 'fa-codepen','title' => 'Codepen');
			$fonts[] = array('class' => 'fa-jsfiddle','title' => 'JsFiddle');
			$fonts[] = array('class' => 'fa-life-bouy','title' => 'Life Bouy');
			$fonts[] = array('class' => 'fa-life-buoy','title' => 'Life Buoy');
			$fonts[] = array('class' => 'fa-life-saver','title' => 'Life Saver');
			$fonts[] = array('class' => 'fa-support','title' => 'Support');
			$fonts[] = array('class' => 'fa-life-ring','title' => 'Life Ring');
			$fonts[] = array('class' => 'fa-circle-o-notch','title' => 'Circle O Notch');
			$fonts[] = array('class' => 'fa-ra','title' => 'Ra');
			$fonts[] = array('class' => 'fa-resistance','title' => 'Resistance');
			$fonts[] = array('class' => 'fa-rebel','title' => 'Rebel');
			$fonts[] = array('class' => 'fa-ge','title' => 'Ge');
			$fonts[] = array('class' => 'fa-empire','title' => 'Empire');
			$fonts[] = array('class' => 'fa-git-square','title' => 'Git Square');
			$fonts[] = array('class' => 'fa-git','title' => 'Git');
			$fonts[] = array('class' => 'fa-y-combinator-square','title' => 'Y Combinator Square');
			$fonts[] = array('class' => 'fa-yc-square','title' => 'Yc Square');
			$fonts[] = array('class' => 'fa-hacker-news','title' => 'Hacker News');
			$fonts[] = array('class' => 'fa-tencent-weibo','title' => 'Tencent Weibo');
			$fonts[] = array('class' => 'fa-qq','title' => 'Qq');
			$fonts[] = array('class' => 'fa-wechat','title' => 'WeChat');
			$fonts[] = array('class' => 'fa-weixin','title' => 'Weixin');
			$fonts[] = array('class' => 'fa-send','title' => 'Send');
			$fonts[] = array('class' => 'fa-paper-plane','title' => 'Paper Plane');
			$fonts[] = array('class' => 'fa-send-o','title' => 'Send O');
			$fonts[] = array('class' => 'fa-paper-plane-o','title' => 'Paper Plane O');
			$fonts[] = array('class' => 'fa-history','title' => 'History');
			$fonts[] = array('class' => 'fa-circle-thin','title' => 'Circle Thin');
			$fonts[] = array('class' => 'fa-header','title' => 'Header');
			$fonts[] = array('class' => 'fa-paragraph','title' => 'Paragraph');
			$fonts[] = array('class' => 'fa-sliders','title' => 'Sliders');
			$fonts[] = array('class' => 'fa-share-alt','title' => 'Share Alt');
			$fonts[] = array('class' => 'fa-share-alt-square','title' => 'Share Alt Square');
			$fonts[] = array('class' => 'fa-bomb','title' => 'Bomb');
			$fonts[] = array('class' => 'fa-soccer-ball-o','title' => 'Soccer Ball O');
			$fonts[] = array('class' => 'fa-futbol-o','title' => 'Futbol O');
			$fonts[] = array('class' => 'fa-tty','title' => 'Tty');
			$fonts[] = array('class' => 'fa-binoculars','title' => 'Binoculars');
			$fonts[] = array('class' => 'fa-plug','title' => 'Plug');
			$fonts[] = array('class' => 'fa-slideshare','title' => 'Slideshare');
			$fonts[] = array('class' => 'fa-twitch','title' => 'Twitch');
			$fonts[] = array('class' => 'fa-yelp','title' => 'Yelp');
			$fonts[] = array('class' => 'fa-newspaper-o','title' => 'Newspaper O');
			$fonts[] = array('class' => 'fa-wifi','title' => 'Wifi');
			$fonts[] = array('class' => 'fa-calculator','title' => 'Calculator');
			$fonts[] = array('class' => 'fa-paypal','title' => 'Paypal');
			$fonts[] = array('class' => 'fa-google-wallet','title' => 'Google Wallet');
			$fonts[] = array('class' => 'fa-cc-visa','title' => 'CC Visa');
			$fonts[] = array('class' => 'fa-cc-mastercard','title' => 'CC Mastercard');
			$fonts[] = array('class' => 'fa-cc-discover','title' => 'CC Discover');
			$fonts[] = array('class' => 'fa-cc-amex','title' => 'CC Amex');
			$fonts[] = array('class' => 'fa-cc-paypal','title' => 'CC Paypal');
			$fonts[] = array('class' => 'fa-cc-stripe','title' => 'CC Stripe');
			$fonts[] = array('class' => 'fa-bell-slash','title' => 'Bell Slash');
			$fonts[] = array('class' => 'fa-bell-slash-o','title' => 'Bell Slash O');
			$fonts[] = array('class' => 'fa-copyright','title' => 'Copyright');
			$fonts[] = array('class' => 'fa-at','title' => 'At');
			$fonts[] = array('class' => 'fa-eyedropper','title' => 'EyeDropper');
			$fonts[] = array('class' => 'fa-paint-brush','title' => 'Paint Brush');
			$fonts[] = array('class' => 'fa-birthday-cake','title' => 'Birthday Cake');
			$fonts[] = array('class' => 'fa-area-chart','title' => 'Area Chart');
			$fonts[] = array('class' => 'fa-pie-chart','title' => 'Pie Chart');
			$fonts[] = array('class' => 'fa-line-chart','title' => 'Line Chart');
			$fonts[] = array('class' => 'fa-lastfm','title' => 'LastFM');
			$fonts[] = array('class' => 'fa-lastfm-square','title' => 'LastFM Square');
			$fonts[] = array('class' => 'fa-toggle-off','title' => 'Toggle Off');
			$fonts[] = array('class' => 'fa-toggle-on','title' => 'Toggle On');
			$fonts[] = array('class' => 'fa-bicycle','title' => 'Bicycle');
			$fonts[] = array('class' => 'fa-bus','title' => 'Bus');
			$fonts[] = array('class' => 'fa-ioxhost','title' => 'Ioxhost');
			$fonts[] = array('class' => 'fa-angellist','title' => 'Angellist');
			$fonts[] = array('class' => 'fa-cc','title' => 'CC');
			$fonts[] = array('class' => 'fa-shekel','title' => 'Shekel');
			$fonts[] = array('class' => 'fa-sheqel','title' => 'Sheqel');
			$fonts[] = array('class' => 'fa-ils','title' => 'ILS');
			$fonts[] = array('class' => 'fa-meanpath','title' => 'MeanPath');
			$fonts[] = array('class' => 'fa-buysellads','title' => 'BuySellAds');
			$fonts[] = array('class' => 'fa-connectdevelop','title' => 'ConnectDevelop');
			$fonts[] = array('class' => 'fa-dashcube','title' => 'DashCube');
			$fonts[] = array('class' => 'fa-forumbee','title' => 'ForumBee');
			$fonts[] = array('class' => 'fa-leanpub','title' => 'LeanPub');
			$fonts[] = array('class' => 'fa-sellsy','title' => 'Sellsy');
			$fonts[] = array('class' => 'fa-shirtsinbulk','title' => 'ShirtsInBulk');
			$fonts[] = array('class' => 'fa-simplybuilt','title' => 'SimplyBuilt');
			$fonts[] = array('class' => 'fa-skyatlas','title' => 'SkyAtlas');
			$fonts[] = array('class' => 'fa-cart-plus','title' => 'Cart Plus');
			$fonts[] = array('class' => 'fa-cart-arrow-down','title' => 'Cart Arrow Down');
			$fonts[] = array('class' => 'fa-diamond','title' => 'Diamond');
			$fonts[] = array('class' => 'fa-ship','title' => 'Ship');
			$fonts[] = array('class' => 'fa-user-secret','title' => 'User Secret');
			$fonts[] = array('class' => 'fa-motorcycle','title' => 'Motorcycle');
			$fonts[] = array('class' => 'fa-street-view','title' => 'Street View');
			$fonts[] = array('class' => 'fa-heartbeat','title' => 'Heartbeat');
			$fonts[] = array('class' => 'fa-venus','title' => 'Venus');
			$fonts[] = array('class' => 'fa-mars','title' => 'Mars');
			$fonts[] = array('class' => 'fa-mercury','title' => 'Mercury');
			$fonts[] = array('class' => 'fa-intersex','title' => 'Intersex');
			$fonts[] = array('class' => 'fa-transgender','title' => 'Transgender');
			$fonts[] = array('class' => 'fa-transgender-alt','title' => 'Transgender Alt');
			$fonts[] = array('class' => 'fa-venus-double','title' => 'Venus Double');
			$fonts[] = array('class' => 'fa-mars-double','title' => 'Mars Double');
			$fonts[] = array('class' => 'fa-venus-mars','title' => 'Venus Mars');
			$fonts[] = array('class' => 'fa-mars-stroke','title' => 'Mars Stroke');
			$fonts[] = array('class' => 'fa-mars-stroke-v','title' => 'Mars Stroke V');
			$fonts[] = array('class' => 'fa-mars-stroke-h','title' => 'Mars Stroke H');
			$fonts[] = array('class' => 'fa-neuter','title' => 'Neuter');
			$fonts[] = array('class' => 'fa-genderless','title' => 'Genderless');
			$fonts[] = array('class' => 'fa-facebook-official','title' => 'Facebook Official');
			$fonts[] = array('class' => 'fa-pinterest-p','title' => 'Pinterest P');
			$fonts[] = array('class' => 'fa-whatsapp','title' => 'WhatsApp');
			$fonts[] = array('class' => 'fa-server','title' => 'Server');
			$fonts[] = array('class' => 'fa-user-plus','title' => 'User Plus');
			$fonts[] = array('class' => 'fa-user-times','title' => 'User Times');
			$fonts[] = array('class' => 'fa-hotel','title' => 'Hotel');
			$fonts[] = array('class' => 'fa-bed','title' => 'Bed');
			$fonts[] = array('class' => 'fa-viacoin','title' => 'ViaCoin');
			$fonts[] = array('class' => 'fa-train','title' => 'Train');
			$fonts[] = array('class' => 'fa-subway','title' => 'Subway');
			$fonts[] = array('class' => 'fa-medium','title' => 'Medium');
			$fonts[] = array('class' => 'fa-yc','title' => 'Yc');
			$fonts[] = array('class' => 'fa-y-combinator','title' => 'Y Combinator');
			$fonts[] = array('class' => 'fa-optin-monster','title' => 'Optin Monster');
			$fonts[] = array('class' => 'fa-opencart','title' => 'Opencart');
			$fonts[] = array('class' => 'fa-expeditedssl','title' => 'Expedited SSL');
			$fonts[] = array('class' => 'fa-battery-4','title' => 'Battery 4');
			$fonts[] = array('class' => 'fa-battery-full','title' => 'Battery Full');
			$fonts[] = array('class' => 'fa-battery-3','title' => 'Battery 3');
			$fonts[] = array('class' => 'fa-battery-three-quarters','title' => 'Battery Three Quarters');
			$fonts[] = array('class' => 'fa-battery-2','title' => 'Battery 2');
			$fonts[] = array('class' => 'fa-battery-half','title' => 'Battery Half');
			$fonts[] = array('class' => 'fa-battery-1','title' => 'Battery 1');
			$fonts[] = array('class' => 'fa-battery-quarter','title' => 'Battery Quarter');
			$fonts[] = array('class' => 'fa-battery-0','title' => 'Battery 0');
			$fonts[] = array('class' => 'fa-battery-empty','title' => 'Battery Empty');
			$fonts[] = array('class' => 'fa-mouse-pointer','title' => 'Mouse Pointer');
			$fonts[] = array('class' => 'fa-i-cursor','title' => 'I Cursor');
			$fonts[] = array('class' => 'fa-object-group','title' => 'Object Group');
			$fonts[] = array('class' => 'fa-object-ungroup','title' => 'Object Ungroup');
			$fonts[] = array('class' => 'fa-sticky-note','title' => 'Sticky Note');
			$fonts[] = array('class' => 'fa-sticky-note-o','title' => 'Sticky Note O');
			$fonts[] = array('class' => 'fa-cc-jcb','title' => 'CC JCB');
			$fonts[] = array('class' => 'fa-cc-diners-club','title' => 'CC Diners Club');
			$fonts[] = array('class' => 'fa-clone','title' => 'Clone');
			$fonts[] = array('class' => 'fa-balance-scale','title' => 'Balance Scale');
			$fonts[] = array('class' => 'fa-hourglass-o','title' => 'Hourglass O');
			$fonts[] = array('class' => 'fa-hourglass-1','title' => 'Hourglass 1');
			$fonts[] = array('class' => 'fa-hourglass-start','title' => 'Hourglass Start');
			$fonts[] = array('class' => 'fa-hourglass-2','title' => 'Hourglass 2');
			$fonts[] = array('class' => 'fa-hourglass-half','title' => 'Hourglass Half');
			$fonts[] = array('class' => 'fa-hourglass-3','title' => 'Hourglass 3');
			$fonts[] = array('class' => 'fa-hourglass-end','title' => 'Hourglass End');
			$fonts[] = array('class' => 'fa-hourglass','title' => 'Hourglass');
			$fonts[] = array('class' => 'fa-hand-grab-o','title' => 'Hand Grab O');
			$fonts[] = array('class' => 'fa-hand-rock-o','title' => 'Hand Rock O');
			$fonts[] = array('class' => 'fa-hand-stop-o','title' => 'Hand Stop O');
			$fonts[] = array('class' => 'fa-hand-paper-o','title' => 'Hand Paper O');
			$fonts[] = array('class' => 'fa-hand-scissors-o','title' => 'Hand Scissors O');
			$fonts[] = array('class' => 'fa-hand-lizard-o','title' => 'Hand Lizard O');
			$fonts[] = array('class' => 'fa-hand-spock-o','title' => 'Hand Spock O');
			$fonts[] = array('class' => 'fa-hand-pointer-o','title' => 'Hand Pointer O');
			$fonts[] = array('class' => 'fa-hand-peace-o','title' => 'Hand Peace O');
			$fonts[] = array('class' => 'fa-trademark','title' => 'Trademark');
			$fonts[] = array('class' => 'fa-registered','title' => 'Registered');
			$fonts[] = array('class' => 'fa-creative-commons','title' => 'Creative Commons');
			$fonts[] = array('class' => 'fa-gg','title' => 'Gg');
			$fonts[] = array('class' => 'fa-gg-circle','title' => 'Gg Circle');
			$fonts[] = array('class' => 'fa-tripadvisor','title' => 'TripAdvisor');
			$fonts[] = array('class' => 'fa-odnoklassniki','title' => 'Odnoklassniki');
			$fonts[] = array('class' => 'fa-odnoklassniki-square','title' => 'Odnoklassniki Square');
			$fonts[] = array('class' => 'fa-get-pocket','title' => 'Get Pocket');
			$fonts[] = array('class' => 'fa-wikipedia-w','title' => 'Wikipedia W');
			$fonts[] = array('class' => 'fa-safari','title' => 'Safari');
			$fonts[] = array('class' => 'fa-chrome','title' => 'Chrome');
			$fonts[] = array('class' => 'fa-firefox','title' => 'Firefox');
			$fonts[] = array('class' => 'fa-opera','title' => 'Opera');
			$fonts[] = array('class' => 'fa-internet-explorer','title' => 'Internet Explorer');
			$fonts[] = array('class' => 'fa-tv','title' => 'Tv');
			$fonts[] = array('class' => 'fa-television','title' => 'Television');
			$fonts[] = array('class' => 'fa-contao','title' => 'Contao');
			$fonts[] = array('class' => 'fa-500px','title' => '500px');
			$fonts[] = array('class' => 'fa-amazon','title' => 'Amazon');
			$fonts[] = array('class' => 'fa-calendar-plus-o','title' => 'Calendar Plus O');
			$fonts[] = array('class' => 'fa-calendar-minus-o','title' => 'Calendar Minus O');
			$fonts[] = array('class' => 'fa-calendar-times-o','title' => 'Calendar Times O');
			$fonts[] = array('class' => 'fa-calendar-check-o','title' => 'Calendar Check O');
			$fonts[] = array('class' => 'fa-industry','title' => 'Industry');
			$fonts[] = array('class' => 'fa-map-pin','title' => 'Map Pin');
			$fonts[] = array('class' => 'fa-map-signs','title' => 'Map Signs');
			$fonts[] = array('class' => 'fa-map-o','title' => 'Map O');
			$fonts[] = array('class' => 'fa-map','title' => 'Map');
			$fonts[] = array('class' => 'fa-commenting','title' => 'Commenting');
			$fonts[] = array('class' => 'fa-commenting-o','title' => 'Commenting O');
			$fonts[] = array('class' => 'fa-houzz','title' => 'Houzz');
			$fonts[] = array('class' => 'fa-vimeo','title' => 'Vimeo');
			$fonts[] = array('class' => 'fa-black-tie','title' => 'Black Tie');
			$fonts[] = array('class' => 'fa-fonticons','title' => 'FontIcons');
			$fonts[] = array('class' => 'fa-reddit-alien','title' => 'Reddit Alien');
			$fonts[] = array('class' => 'fa-edge','title' => 'Edge');
			$fonts[] = array('class' => 'fa-credit-card-alt','title' => 'Credit Card Alt');
			$fonts[] = array('class' => 'fa-codiepie','title' => 'Codiepie');
			$fonts[] = array('class' => 'fa-modx','title' => 'ModX');
			$fonts[] = array('class' => 'fa-fort-awesome','title' => 'Fort Awesome');
			$fonts[] = array('class' => 'fa-usb','title' => 'Usb');
			$fonts[] = array('class' => 'fa-product-hunt','title' => 'Product Hunt');
			$fonts[] = array('class' => 'fa-mixcloud','title' => 'MixCloud');
			$fonts[] = array('class' => 'fa-scribd','title' => 'Scribd');
			$fonts[] = array('class' => 'fa-pause-circle','title' => 'Pause Circle');
			$fonts[] = array('class' => 'fa-pause-circle-o','title' => 'Pause Circle O');
			$fonts[] = array('class' => 'fa-stop-circle','title' => 'Stop Circle');
			$fonts[] = array('class' => 'fa-stop-circle-o','title' => 'Stop Circle O');
			$fonts[] = array('class' => 'fa-shopping-bag','title' => 'Shopping Bag');
			$fonts[] = array('class' => 'fa-shopping-basket','title' => 'Shopping Basket');
			$fonts[] = array('class' => 'fa-hashtag','title' => 'Hashtag');
			$fonts[] = array('class' => 'fa-bluetooth','title' => 'Bluetooth');
			$fonts[] = array('class' => 'fa-bluetooth-b','title' => 'Bluetooth B');
			$fonts[] = array('class' => 'fa-percent','title' => 'Percent');
			$fonts[] = array('class' => 'fa-gitlab','title' => 'Gitlab');
			$fonts[] = array('class' => 'fa-wpbeginner','title' => 'WpBeginner');
			$fonts[] = array('class' => 'fa-wpforms','title' => 'WpForms');
			$fonts[] = array('class' => 'fa-envira','title' => 'Envira');
			$fonts[] = array('class' => 'fa-universal-access','title' => 'Universal Access');
			$fonts[] = array('class' => 'fa-wheelchair-alt','title' => 'Wheelchair Alt');
			$fonts[] = array('class' => 'fa-question-circle-o','title' => 'Question Circle O');
			$fonts[] = array('class' => 'fa-blind','title' => 'Blind');
			$fonts[] = array('class' => 'fa-audio-description','title' => 'Audio Description');
			$fonts[] = array('class' => 'fa-volume-control-phone','title' => 'Volume Control Phone');
			$fonts[] = array('class' => 'fa-braille','title' => 'Braille');
			$fonts[] = array('class' => 'fa-assistive-listening-systems','title' => 'Assistive Listening Systems');
			$fonts[] = array('class' => 'fa-asl-interpreting','title' => 'Asl Interpreting');
			$fonts[] = array('class' => 'fa-american-sign-language-interpreting','title' => 'American Sign Language Interpreting');
			$fonts[] = array('class' => 'fa-deafness','title' => 'Deafness');
			$fonts[] = array('class' => 'fa-hard-of-hearing','title' => 'Hard of Hearing');
			$fonts[] = array('class' => 'fa-deaf','title' => 'Deaf');
			$fonts[] = array('class' => 'fa-glide','title' => 'Glide');
			$fonts[] = array('class' => 'fa-glide-g','title' => 'Glide G');
			$fonts[] = array('class' => 'fa-signing','title' => 'Signing');
			$fonts[] = array('class' => 'fa-sign-language','title' => 'Sign Language');
			$fonts[] = array('class' => 'fa-low-vision','title' => 'Low Vision');
			$fonts[] = array('class' => 'fa-viadeo','title' => 'Viadeo');
			$fonts[] = array('class' => 'fa-viadeo-square','title' => 'Viadeo Square');
			$fonts[] = array('class' => 'fa-snapchat','title' => 'SnapChat');
			$fonts[] = array('class' => 'fa-snapchat-ghost','title' => 'SnapChat Ghost');
			$fonts[] = array('class' => 'fa-snapchat-square','title' => 'SnapChat Square');
			$fonts[] = array('class' => 'fa-pied-piper','title' => 'Pied Piper');
			$fonts[] = array('class' => 'fa-first-order','title' => 'First Order');
			$fonts[] = array('class' => 'fa-yoast','title' => 'Yoast');
			$fonts[] = array('class' => 'fa-themeisle','title' => 'Theme Isle');
			$fonts[] = array('class' => 'fa-google-plus-circle','title' => 'Google Plus Circle');
			$fonts[] = array('class' => 'fa-google-plus-official','title' => 'Google Plus Official');
			$fonts[] = array('class' => 'fa-fa','title' => 'Fa');
			$fonts[] = array('class' => 'fa-font-awesome','title' => 'Font Awesome');
			$fonts[] = array('class' => 'fa-handshake-o','title' => 'Handshake O');
			$fonts[] = array('class' => 'fa-envelope-open','title' => 'Envelope Open');
			$fonts[] = array('class' => 'fa-envelope-open-o','title' => 'Envelope Open O');
			$fonts[] = array('class' => 'fa-linode','title' => 'Linode');
			$fonts[] = array('class' => 'fa-address-book','title' => 'Address Book');
			$fonts[] = array('class' => 'fa-address-book-o','title' => 'Address Book O');
			$fonts[] = array('class' => 'fa-vcard','title' => 'Vcard');
			$fonts[] = array('class' => 'fa-address-card','title' => 'Address Card');
			$fonts[] = array('class' => 'fa-vcard-o','title' => 'Vcard O');
			$fonts[] = array('class' => 'fa-address-card-o','title' => 'Address Card O');
			$fonts[] = array('class' => 'fa-user-circle','title' => 'User Circle');
			$fonts[] = array('class' => 'fa-user-circle-o','title' => 'User Circle O');
			$fonts[] = array('class' => 'fa-user-o','title' => 'User O');
			$fonts[] = array('class' => 'fa-id-badge','title' => 'Id Badge');
			$fonts[] = array('class' => 'fa-drivers-license','title' => 'Drivers License');
			$fonts[] = array('class' => 'fa-id-card','title' => 'Id Card');
			$fonts[] = array('class' => 'fa-drivers-license-o','title' => 'Drivers License O');
			$fonts[] = array('class' => 'fa-id-card-o','title' => 'Id Card O');
			$fonts[] = array('class' => 'fa-quora','title' => 'Quora');
			$fonts[] = array('class' => 'fa-free-code-camp','title' => 'Free Code Camp');
			$fonts[] = array('class' => 'fa-telegram','title' => 'Telegram');
			$fonts[] = array('class' => 'fa-thermometer-4','title' => 'Thermometer 4');
			$fonts[] = array('class' => 'fa-thermometer','title' => 'Thermometer');
			$fonts[] = array('class' => 'fa-thermometer-full','title' => 'Thermometer Full');
			$fonts[] = array('class' => 'fa-thermometer-3','title' => 'Thermometer 3');
			$fonts[] = array('class' => 'fa-thermometer-three-quarters','title' => 'Thermometer Three Quarters');
			$fonts[] = array('class' => 'fa-thermometer-2','title' => 'Thermometer 2');
			$fonts[] = array('class' => 'fa-thermometer-half','title' => 'Thermometer Half');
			$fonts[] = array('class' => 'fa-thermometer-1','title' => 'Thermometer 1');
			$fonts[] = array('class' => 'fa-thermometer-quarter','title' => 'Thermometer Quarter');
			$fonts[] = array('class' => 'fa-thermometer-0','title' => 'Thermometer 0');
			$fonts[] = array('class' => 'fa-thermometer-empty','title' => 'Thermometer Empty');
			$fonts[] = array('class' => 'fa-shower','title' => 'Shower');
			$fonts[] = array('class' => 'fa-bathtub','title' => 'Bathtub');
			$fonts[] = array('class' => 'fa-s15','title' => 'S15');
			$fonts[] = array('class' => 'fa-bath','title' => 'Bath');
			$fonts[] = array('class' => 'fa-podcast','title' => 'Podcast');
			$fonts[] = array('class' => 'fa-window-maximize','title' => 'Window Maximize');
			$fonts[] = array('class' => 'fa-window-minimize','title' => 'Window Minimize');
			$fonts[] = array('class' => 'fa-window-restore','title' => 'Window Restore');
			$fonts[] = array('class' => 'fa-times-rectangle','title' => 'Times Rectangle');
			$fonts[] = array('class' => 'fa-window-close','title' => 'Window Close');
			$fonts[] = array('class' => 'fa-times-rectangle-o','title' => 'Times Rectangle O');
			$fonts[] = array('class' => 'fa-window-close-o','title' => 'Window Close O');
			$fonts[] = array('class' => 'fa-bandcamp','title' => 'Bandcamp');
			$fonts[] = array('class' => 'fa-grav','title' => 'Grav');
			$fonts[] = array('class' => 'fa-etsy','title' => 'Etsy');
			$fonts[] = array('class' => 'fa-imdb','title' => 'Imdb');
			$fonts[] = array('class' => 'fa-ravelry','title' => 'Ravelry');
			$fonts[] = array('class' => 'fa-eercast','title' => 'Eercast');
			$fonts[] = array('class' => 'fa-microchip','title' => 'Microchip');
			$fonts[] = array('class' => 'fa-snowflake-o','title' => 'Snowflake O');
			$fonts[] = array('class' => 'fa-superpowers','title' => 'Superpowers');
			$fonts[] = array('class' => 'fa-wpexplorer','title' => 'Wpexplorer');
			$fonts[] = array('class' => 'fa-meetup','title' => 'Meetup');

			sort($fonts);

			$this->cache->set('fonts', $fonts);
		}

		return $fonts;
	}
}
